### ISSUE TITLE
appId should be included in the signParams return value of the deploy method of the deployment app

### ISSUE THREAD

**Issue by abramsymons** [muon-protocol/muon-node-js#105]
Not including `appId` which is being deployed in the return value of `signParams` here seems to raise potential security concerns.
https://github.com/muon-protocol/muon-node-js/blob/15df2a9c31e2084184190fec055ab1d21fa3de4c/src/built-in-apps/app-deployment.js#L402-L418

**Comment by sadeghte** [comment]
By default, appId and reqId are included in all app's signing parameters. BaseAppPlugin has a method named `appendSecurityParams` to prepend these two parameters to user-defined parameters.

```typescript
appendSecurityParams(request, signParams) {
    return [
      { name: "appId", type: 'uint256', value: this.APP_ID },
      { name: "reqId", type: 'uint256', value: request.reqId },
      ...signParams
    ]
  }
```
