### ISSUE TITLE
Use more reliable library for random generation

### ISSUE THREAD

**Issue by abramsymons** [muon-protocol/muon-node-js#107]
`rand-seed` that is used [here](https://github.com/muon-protocol/muon-node-js/blob/15df2a9c31e2084184190fec055ab1d21fa3de4c/src/core/plugins/system.ts#LL26C1-L26C1) does not seems like a well-known and reliable library for generating random numbers:
https://www.npmjs.com/package/rand-seed

**Comment by fofaraz** [comment]
I have reviewed this package. The dependencies of this package are reliable; they consist of code formatters, package shipping helpers, and a test runner. This package implements several well-known random seed algorithms, which are relatively simple. 
By the way, it is possible to remove this package and implement one of the random seed algorithms in our own code.

**Comment by bakhshandeh** [comment]
It’s a very light and standalone lib and does not depend on any other big lib.
We can audit it later

let’s close this issue for now
