### ISSUE TITLE
remove unused modules from package.json

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#194]
These packages and other unused packages on devDependencies should be removed.
"enzyme": "^3.11.0",
"enzyme-adapter-react-16": "^1.15.6"

**Comment by bakhshandeh** [comment]
Here is the `depcheck` result:

```
$ depcheck 
Unused dependencies
* @libp2p/interface-peer-discovery
* datastore-level
* debug
* ethereum-cryptography
* ipfs-http-client
* tslib
Missing dependencies
* @libp2p/peer-id-factory: ./testnet-generate-env.js
* @libp2p/crypto: ./testnet-generate-env.js
* @libp2p/logger: ./src/index.ts
* private-ip: ./src/utils/helpers.ts
* ethereumjs-util: ./src/utils/tss/index.ts
* p-queue: ./src/network/muon-routing.ts
* p-defer: ./src/network/muon-routing.ts
* err-code: ./src/network/muon-routing.ts
* any-signal: ./src/network/muon-routing.ts
* @libp2p/interface-peer-id: ./src/network/muon-routing.ts
* ipfs-core-types: ./src/network/muon-routing.ts
* @libp2p/interface-peer-routing: ./src/network/muon-routing.ts
* @libp2p/interface-peer-info: ./src/network/muon-routing.ts
* @libp2p/interfaces: ./src/network/muon-routing.ts
* @multiformats/multiaddr: ./src/network/muon-routing.ts
* @libp2p/interface-peer-store: ./src/network/types.ts
* https-proxy-agent: ./apps/general/crypto_v3.js
```

**Comment by fofaraz** [comment]
npm-check 
Not used:
@libp2p/interface-peer-discovery
datastore-level 
debug
ethereum-cryptography 
ipfs-http-client
tslib

Major update:
@chainsafe/libp2p-gossipsub 
@ipld/dag-pb 
axios
dotenv
ethers
it-drain
it-last 
it-pipe 
metaapi.cloud-sdk 
mkdirp
mongoose
multiformats
nodemon
redis
tronweb
uint8arrays
ws
@types/node
chalk
jest
node-emoji 
typescript

**Comment by bakhshandeh** [comment]
More updates on packages.json:
•  Remove jest
•  Fix license
•  Check all scripts
•  Fix devDependencies
•  Remove nodemon or move it to devDeps
•  Remove node-emoji
•  Remove ws

**Comment by fofaraz** [comment]
eth-sig-util package is deprecated but some apps are using its functions
