### ISSUE TITLE
"peer not found" timeout

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#224]
```
{u'result': {u'peerInfo': {u'multiaddrs': [u'/ip4/45.132.246.20/tcp/4000/p2p/QmQkGqzrki6Rhp2mC3rFgJSJYZPM4Q2hRpBEsZDUc7gscw'], u'id': u'QmQkGqzrki6Rhp2mC3rFgJSJYZPM4Q2hRpBEsZDUc7gscw', u'protocols': []}, u'nodeInfo': u'peer not found peerId: QmQkGqzrki6Rhp2mC3rFgJSJYZPM4Q2hRpBEsZDUc7gscw', u'execTime': 30006}, u'success': True}
```

execTime of `peer not found` errs is too long

**Comment by fofaraz** [comment]
Currently timeout limit is being reached because one of the delegate servers is down. 
I have tested this, If all delegate servers respond in time, it will throw `peer not found` much faster and wont reach timeout limit.
