### ISSUE TITLE
deployment error(from cmd)

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#234]
error: { message: 'key-gen starter node not online', onRemoteSide: true }

PARTY:

{ "_id" : ObjectId("64cd0ef96a0fed2cfe9752cf"), "party" : { "partners" : [ "811", "5433", "13747", "16799", "11132", "17122", "21802", "19510", "19215", "17667", "20061", "110", "16547", "19825", "12076", "21602", "18678", "6103", "10458", "20434" ], "t" : 7, "max" : 20 } }

**Comment by fofaraz** [comment]
this issue is fixed in this commit
https://github.com/muon-protocol/muon-node-js/commit/4d4fb150948b3089bd49e2ebb5a0d09d895d5553

I've tested it several times, the error seems to be resolved now
