### ISSUE TITLE
Bug: set timeout for requests on gateway

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#236]
```
# time curl -g 'http://104.131.177.195:8080/v1/?app=simple_oracle&method=price&params[token]=usdt&params[unit]=USD'
```

When one or more nodes in a party are unstable, the requests hang up. There should be a timeout and an error message should be sent after some time.

**Comment by bakhshandeh** [comment]
@sadeghte we agreed to set a fixed timeout and remove the code that tries to find a dynamic timeout.
Is it done?

**Comment by sadeghte** [comment]
Done.
