### ISSUE TITLE
Improve delegation service performance

### ISSUE THREAD

**Issue by abramsymons** [muon-protocol/muon-node-js#273]
Currently delegation service is one of the heaviest services in the Muon network which puts a very high load on servers of delegate nodes.

Verification of the signature is the CPU-intensive part of requests that thousands of nodes are sending to this service periodically.

https://github.com/muon-protocol/muon-node-js/blob/c8471bb7df3f25fa361c87b616e0f831c5a48d56/src/gateway/delegate-routing.ts#L169-L180

Service performance can be drastically improved if this verification is done only when some node data are changed.

**Comment by bakhshandeh** [comment]
Disabling the verification even when data is not changed is not secure. It lets hackers send requests on behalf of the nodes that are not online, and the delegates will consider offline nodes as online. This could cause some issues.

The web APIs on the nodes are not using SSL or any kinds of encryption and the data on all of the endpoints should be verifiable.

**Comment by bakhshandeh** [comment]
I think the issue with delegate nodes is not a big problem. It could be solved by increasing the resources.

Another good solution is to implement a simple Sharding algorithm. Currently, all of the nodes are sending data to all of the delegates. With Sharding, each node will select a subset of delegate nodes using a deterministic algorithm and the nodes that want to query the PeerInfo can find the correct subset using the same algorithm.

With 10 nodes and subset size 4, the load of the nodes will be decreased by 60%,
