### ISSUE TITLE
Context not found bug

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#283]
Monitoring service still reports this err:

{'success': False, 'appId': '55248038324285368712633359989377918216711324138169494581107010692219814301235', 'error': {'message': "App's context not found.", 'onRemoteSide': True}}

need to debug and see what's the problem.
Possible issues:
1- resharing can't be done on time. The logs on deployers should be checked
2- forwarding requests to party nodes is buggy and sometimes send requests to the nodes that can't handle the requests

**Comment by fofaraz** [comment]
Now that network has more deployers this error is happening a lot less (about once every couple of days)

**Comment by bakhshandeh** [comment]
FIXED
