### ISSUE TITLE
latency check plugin improvement

### ISSUE THREAD

**Issue by sadeghte** [muon-protocol/muon-node-js#289]
The `latency-check` plugin is a tool that periodically monitors the status and performance of the nodes in the network. When a new app is deployed, it adds the new nodes of the app to the check list. However, these new nodes are not checked by the latency-check plugin until the next scheduled interval. This means that during this time, if a request is sent to the app party, it may fail because the new nodes are not ready or reachable. To improve the latency-check plugin, it can be modified to perform an immediate check right after a new app is deployed. This way, any node in the network that sees a new node in its common subset of network will initiate a health check to measure its latency. This will ensure that the new nodes are quickly integrated and verified by the network.

**Comment by bakhshandeh** [comment]
Usually, the request will be handled by the oldest context. This gives the new context some time to update the latency data.

**Comment by sadeghte** [comment]
"When the context is being reshared, this is correct. However, when the app is deployed for the first time, the problem occurs.

**Comment by bakhshandeh** [comment]
Agreed to not work on this
