### ISSUE TITLE
Db sync improvements

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#306]
When non deployers ask deployers to confirm that a context is expired and should be removed, they should get a confirmation from more than one node.

Currently just one response is checking and it could cause issues when deployers that are not synced send the responses.

**Comment by sadeghte** [comment]
fixed in [2bafe13](https://github.com/muon-protocol/muon-node-js/commit/2bafe1312b1258796836f96b41a6c7cd50dadb92)
