### ISSUE TITLE
is it necessary to close the streams?

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#323]
https://github.com/muon-protocol/muon-node-js/blob/575c00845d54dae7df96a1a7ede5f878f5cfefa3/src/network/plugins/remote-call.ts#L112

Should the streams be closed here?

**Comment by fofaraz** [comment]
In most lib p2p official examples it does not close the stream, 
only in one example it closes like this:

```
await pipe(
        stream,...
      ).finally(() => {
      // clean up resources
      stream.close()
    })
```

seems like this way it does not affect any functionality
i will try to test this in a loop call and compare if closing or not closing it affects memory usage

**Comment by bakhshandeh** [comment]
@fofaraz, let's close the streams and give it a try.
If the speed is fine and the number of failed requests is not more than the old codes, we can close the streams.
