### ISSUE TITLE
bug: must have required property 'broadcast'

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#347]
1|muon-node-js-pion  | 2023-10-24 09:29: 2023-10-24T09:29:12.217Z muon:core:jobs:ReshareCronJob:error tss-rotate request failed { message: `KeyRedistribution needs 7 partners but only [212,811,1263,1387] are qualified. partners=[839,811,1278,1263,1408,212,468,1387,1380,48,263,1257,1196,920,1427,1306,579,410,1459,1443], round=round1, partyErrors={"48":"\\"must have required property 'broadcast'\\"","263":"\\"must have required property 'broadcast'\\"","468":"\\"must have required property 'broadcast'\\"","839":"\\"must have required property 'broadcast'\\"","1278":"{\\"message\\":\\"Error: stream ended before 1 bytes became available\\",\\"stack\\":\\"CodeError: Error: stream ended before 1 bytes became available\\\\n    at DefaultUpgrader._encryptOutbound (file:///usr/src/muon-node-js/node_modules/libp2p/src/upgrader.ts:642:13)\\\\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\\\\n    at async DefaultUpgrader.upgradeOutbound (file:///usr/src/muon-node-js/node_modules/libp2p/src/upgrader.ts:309:13)\\\\n    at async TCP.dial (file:///usr/src/muon-node-js/node_modules/@libp2p/tcp/src/index.ts:127:18)\\\\n    at async DefaultTransportManager.dial (file:///usr/src/muon-node-js/node_modules/libp2p/src/transport-manager.ts:123:14)\\\\n    at async queue.add (file:///usr/src/muon-node-js/node_modules/libp2p/src/connection-manager/dial-queue.ts:467:28)\\\\n    at async file:///usr/src/muon-node-js/node_modules/p-queue/dist/index.js:118:36\\",\\"code\\":\\"ERR_ENCRYPTION_FAILED\\",\\"props\\":{},\\"name\\":\\"CodeError\\",\\"onRemoteSide\\":true}","1380":"\\"must have required property 'broadcast'\\"","1408":"\\"must have required property 'broadcast'\\""} currentNode=0xf07C11d3CfeCDd29920523DC22AfD01E2121Ca96`, mpcExecDebugs: { start: { qualifiedPartners: [Array] }, round1: { roundErrors: [Object], qualifieds: [Array] } }, onRemoteSide: true }

**Comment by bakhshandeh** [comment]
Reshare is throwing this error sometimes

**Comment by bakhshandeh** [comment]
Context:

{ "_id" : ObjectId("65376f6a8c72390074ed4212"), "isBuiltIn" : false, "rotationEnabled" : true, "appId" : "45810160343022089601028851206408642627529628329831086458846511772841706178168", "appName" : "tss", "previousSeed" : "0x817ea3f202baf0aa4968ec6e844f55432d8bc63a01286c06cbd53d45ae1907c7", "seed" : "0xdab664fa3f007c0bcabd71a80d5dd4b45821823ee62869e4c57981c0335fcbb2", "party" : { "partners" : [ "563", "811", "654", "404", "1142", "212", "935", "468", "1263", "1387", "237", "839", "554", "626", "48", "1380", "1278", "263", "1408", "1080" ], "t" : 7, "max" : 20 }, "ttl" : 600, "pendingPeriod" : 600, "expiration" : 1698132937, "deploymentRequest" : { "confirmed" : true, "reqId" : "0x50c1d615abe44a08c73af1694a406bb0108a4f6ed061b4c9afd75733f34ebe07", "app" : "deployment", "appId" : "1", "method" : "reshare", "deploymentSeed" : "0x7c7cb81f3a6185f5da1934e6f1b876da77be738bfc79484597c5156e9d7e4732", "nSign" : 7, "gwAddress" : "0x38c7Df3f9f00F38667E54edEE7A1d2caec03cE31", "data" : { "uid" : "1hdg8jutvf9j73m", "params" : { "appId" : "45810160343022089601028851206408642627529628329831086458846511772841706178168", "previousSeed" : "0x817ea3f202baf0aa4968ec6e844f55432d8bc63a01286c06cbd53d45ae1907c7", "seed" : { "value" : "0xdab664fa3f007c0bcabd71a80d5dd4b45821823ee62869e4c57981c0335fcbb2", "reqId" : "0xe853e1f1e88d6cb0a1e19a8527d4835e2deac1ac0e6913a2fe658b44318ab2ae", "nonce" : "0xEaF780Ee80dA7aa51d6a0E0bf4C54718e260c4c5" }, "leaderSignature" : "0x45b4a95860480d4293eea28c75249389a0335e9ca5e9b62fb97b5e4344352e057b4b0e49aef684c5f0d0382c346e2639a484c53bfd0c6862c1f2be68b931d7891c" }, "timestamp" : 1698131737, "init" : { "key" : { "id" : "resharing-1hdg8k700q1g73n", "publicKey" : "023e5f3e1b07a7e5e5776afadee790cec6385263c90d7dbac23371b1b827cff548", "generators" : [ "212", "237", "404", "563", "654", "811", "935", "1263", "1387" ], "shareProofs" : { "212" : "0x76cfe4a111b82de2bb4be25bd390b3e9201ec0171ed68fed201e100d319b76d3415ee891bb360c6e7a017c20dba6c35156366104ce6dc9c780f4ce56948602201c", "404" : "0x527b033fbcc270ea76e61e0af9b85a95f8a48d581c6ce85707eecfb63441dfd619522e89acccc3584920e8a307b6872210305d79333c305c1d5e7708a5ad5e201c", "563" : "0xab0de6764b7550707c42b1f3237ab3a751be2498209d0e872e61bec1333d1df34a0493d6c74e3f758a23ad03e0fd854f3038537d6eba45a44db35cd62875fd951c", "654" : "0x7033daf3a74eb7adb6024e5181319043d565877c350904e4c62dea20a9022a2674dec07fe37ee39983e67fd18118b5a84e738ec0f0ba20fc13c6de6affeaee301c", "811" : "0xd9728cca4b503fd8829e116bc8b2a1bf14ccef8c7e82be31fec2ea17bb929dd702151c12e1f062e7cd1466d7e74546909f13dbffc1a8e087106de99ce5890a461c", "1263" : "0x337c61f442a4a4637aa76711fe27fbbb7164a3d59be8b9925e85d506572e2cb353445a65824b30f8da27e950b8938072a8267b78386b7a33b5737f2ca7322b631b", "1387" : "0x7ee9b185d7e3d19ccf5a57cc78f7ec0daa38e89d72519ab429cdf9e715bdada7492887f421a396653dec60c40a1f23868cd679ae01fbaab9481d5ff6bc8aec331b" } }, "selectedNodes" : [ "563", "811", "654", "404", "1142", "212", "935", "468", "1263", "1387", "237", "839", "554", "626", "48", "1380", "1278", "263", "1408", "1080" ], "nonceAddress" : "0x0BF0ea865A5AE3BB456CA66b53F2A08F89cd7045" }, "result" : { "rotationEnabled" : true, "ttl" : 600, "pendingPeriod" : 600, "expiration" : 1698132937, "timestamp" : 1698131737, "previousSeed" : "0x817ea3f202baf0aa4968ec6e844f55432d8bc63a01286c06cbd53d45ae1907c7", "seed" : "0xdab664fa3f007c0bcabd71a80d5dd4b45821823ee62869e4c57981c0335fcbb2", "tssThreshold" : 7, "maxGroupSize" : 20, "selectedNodes" : [ "563", "811", "654", "404", "1142", "212", "935", "468", "1263", "1387", "237", "839", "554", "626", "48", "1380", "1278", "263", "1408", "1080" ], "publicKey" : { "address" : "0xb62c40dB7885D74CfdEc65BC04cD31740Eb64508", "encoded" : "023e5f3e1b07a7e5e5776afadee790cec6385263c90d7dbac23371b1b827cff548", "x" : "0x3e5f3e1b07a7e5e5776afadee790cec6385263c90d7dbac23371b1b827cff548", "yParity" : "0" }, "polynomial" : { "t" : 7, "Fx" : [ "023e5f3e1b07a7e5e5776afadee790cec6385263c90d7dbac23371b1b827cff548", "02ab2b9f2d1298e090cadb9e282f018e7df306cfc0dfcc28beca24c0ada943ed5a", "031266da1e99ff9dd2074cceac7b6792f379f1ecc6660c8e5d182cbd662f0778ce", "03968a8dedd79cdad9786a68cfa762c49734ce256d1bfae9047ba16963dfdba308", "033aa349944e3a913ddde4cbe47e59dc37d72086f4afb9f63dbac2de57290ffe34", "032c0585e4879d9866ff8909a6eb145dd3406c923205f75f36cfc5ff0e15e7cb22", "02e59a24a4b6fefe332bdb1ebf407e172e40ece14ff5d56abbd2bd410687542d7b" ] } }, "signParams" : [ { "name" : "appId", "type" : "uint256", "value" : "1" }, { "name" : "reqId", "type" : "uint256", "value" : "0x50c1d615abe44a08c73af1694a406bb0108a4f6ed061b4c9afd75733f34ebe07" }, { "t" : "bool", "v" : true }, { "t" : "uint64", "v" : 600 }, { "t" : "uint64", "v" : 600 }, { "t" : "uint64", "v" : 1698132937 }, { "t" : "uint64", "v" : 1698131737 }, { "t" : "uint256", "v" : "0xdab664fa3f007c0bcabd71a80d5dd4b45821823ee62869e4c57981c0335fcbb2" }, { "t" : "uint64", "v" : "563" }, { "t" : "uint64", "v" : "811" }, { "t" : "uint64", "v" : "654" }, { "t" : "uint64", "v" : "404" }, { "t" : "uint64", "v" : "1142" }, { "t" : "uint64", "v" : "212" }, { "t" : "uint64", "v" : "935" }, { "t" : "uint64", "v" : "468" }, { "t" : "uint64", "v" : "1263" }, { "t" : "uint64", "v" : "1387" }, { "t" : "uint64", "v" : "237" }, { "t" : "uint64", "v" : "839" }, { "t" : "uint64", "v" : "554" }, { "t" : "uint64", "v" : "626" }, { "t" : "uint64", "v" : "48" }, { "t" : "uint64", "v" : "1380" }, { "t" : "uint64", "v" : "1278" }, { "t" : "uint64", "v" : "263" }, { "t" : "uint64", "v" : "1408" }, { "t" : "uint64", "v" : "1080" }, { "t" : "address", "v" : "0xb62c40dB7885D74CfdEc65BC04cD31740Eb64508" }, { "t" : "bytes", "v" : "023e5f3e1b07a7e5e5776afadee790cec6385263c90d7dbac23371b1b827cff548" }, { "t" : "bytes", "v" : "02ab2b9f2d1298e090cadb9e282f018e7df306cfc0dfcc28beca24c0ada943ed5a" }, { "t" : "bytes", "v" : "031266da1e99ff9dd2074cceac7b6792f379f1ecc6660c8e5d182cbd662f0778ce" }, { "t" : "bytes", "v" : "03968a8dedd79cdad9786a68cfa762c49734ce256d1bfae9047ba16963dfdba308" }, { "t" : "bytes", "v" : "033aa349944e3a913ddde4cbe47e59dc37d72086f4afb9f63dbac2de57290ffe34" }, { "t" : "bytes", "v" : "032c0585e4879d9866ff8909a6eb145dd3406c923205f75f36cfc5ff0e15e7cb22" }, { "t" : "bytes", "v" : "02e59a24a4b6fefe332bdb1ebf407e172e40ece14ff5d56abbd2bd410687542d7b" } ], "resultHash" : "0x26dbb0df1957ffacb4a194d1cab45b90d8d6e23036e0d286b22f06c372c06b71" }, "startedAt" : 1698131737, "confirmedAt" : 1698131818, "signatures" : [ { "owner" : "0xfcaAcDe6B88d4273EB93CAd923377145D2c115DF", "ownerPubKey" : { "x" : "0x034d1c4fd7adc1e6fdef1d6509ed9ea05dd3ff37a65c8573a5cdc5fe53fe3420", "yParity" : "0" }, "signature" : "0xa03e073a115d40114afd02a0e5b6d8b5bcf37c128484398c5f9b090fbfbdcf8a" } ] }, "publicKey" : { "address" : "0xb62c40dB7885D74CfdEc65BC04cD31740Eb64508", "encoded" : "023e5f3e1b07a7e5e5776afadee790cec6385263c90d7dbac23371b1b827cff548", "x" : "0x3e5f3e1b07a7e5e5776afadee790cec6385263c90d7dbac23371b1b827cff548", "yParity" : 0 }, "polynomial" : { "Fx" : [ "023e5f3e1b07a7e5e5776afadee790cec6385263c90d7dbac23371b1b827cff548", "02ab2b9f2d1298e090cadb9e282f018e7df306cfc0dfcc28beca24c0ada943ed5a", "031266da1e99ff9dd2074cceac7b6792f379f1ecc6660c8e5d182cbd662f0778ce", "03968a8dedd79cdad9786a68cfa762c49734ce256d1bfae9047ba16963dfdba308", "033aa349944e3a913ddde4cbe47e59dc37d72086f4afb9f63dbac2de57290ffe34", "032c0585e4879d9866ff8909a6eb145dd3406c923205f75f36cfc5ff0e15e7cb22", "02e59a24a4b6fefe332bdb1ebf407e172e40ece14ff5d56abbd2bd410687542d7b" ], "t" : 7 }, "createdAt" : ISODate("2023-10-24T07:16:58.376Z"), "updatedAt" : ISODate("2023-10-24T07:16:58.376Z"), "__v" : 0 }

**Comment by bakhshandeh** [comment]
On above example, the existing context has proofs from these nodes:
['212', '1263', '563', '654', '404', '811', '1387']
Exactly 7 nodes

and the new party is this:
[554,1263,935,1142,1380,48,468,1080,1278,654,1387,1036,949,630,22,918,1459,154,1119,1337]

Only 3 nodes that have proofs are in the new party:
[1263, 654, 1387]


It seems like a bug.
Minimum overlap between the new party and the nodes that have proofs should be at least T.

**Comment by sadeghte** [comment]
resolved in [f06ec44](https://github.com/muon-protocol/muon-node-js/commit/f06ec44145c018b0141911ab0d30fcb339aae2b2)
