### ISSUE TITLE
Update random selection of nodes

### ISSUE THREAD

**Issue by bakhshandeh** [muon-protocol/muon-node-js#75]
https://github.com/muon-protocol/muon-node-js/blob/23f3ea7fd34a9b73d4807dc300a23817f773b19c/src/core/plugins/system.ts#L115-L127

This code is inefficient. It is not necessary to calculate the sha3 of all available nodes. The random selection method should be modified so that:
1- The sha3 calculation is avoided
2- The selection works without issues even if some of the nodes that are not in the selected subnet go offline during the process

**Comment by abramsymons** [comment]
this issue seems to be resolved and can be closed. @bakhshandeh
