### ISSUE TITLE
Unsynchronized clock on party nodes makes problems

### ISSUE THREAD

**Issue by fofaraz** [muon-protocol/muon-node-js#79]
Sometimes the clock on one or more nodes in party of the app isn't set correctly.
This makes problem when that node is selected as gateway and needs to sign a request.
Nodes that their clock is not set correctly must not be selected in the party of the app.

![image](https://user-images.githubusercontent.com/18643641/236665067-a25c7f37-aea4-47c7-b1a7-b5484255decf.png)

**Comment by fofaraz** [comment]
@siftal  we need to check system clock on nodes in  healthcheck tests

**Comment by abramsymons** [comment]
Do we have any way to get the system clock in the monitor service? @sadeghte
