### ISSUE TITLE
Load nodes list from monitor service with a signature from deployers

### ISSUE THREAD

**Issue by abramsymons** [muon-protocol/muon-node-js#85]
Currently nodes load network information from the contract which is a very heavy task.
When the network restarts all thousands of nodes try to load nodes information in pages using a middleware contract that queries all nodes in the page from the node manager contract one by one. This heavy process results in all chain RPC endpoints going down when our network with tens of thousands of nodes restarts.
As an alternative approach, nodes can read those data from the monitor service. To ensure the reliability of the data, a Muon app can be developed to be deployed and run on deployer nodes that load information from the contract every 10 minutes for example and cache the result for the next 10 minutes. Monitor service servers can query this app every 10 minutes and provide the result along with the deployers' signature on that to the other nodes.

**Comment by abramsymons** [comment]
related to https://github.com/muon-protocol/muon-node-js/issues/83

**Comment by bakhshandeh** [comment]
If we remove IPs and other important data from the monitoring service, then it could be a public service.
